apiVersion: skaffold/v2alpha3
kind: Config

deploy:
  kubectl:
    manifests:
        - ./infra/k8s/*

build:
    local:
      push: false # Change this to true when pushing to a remote registry for DigitalOcean
    artifacts:
      - image: ankiitsingh21/jp-admin
        context: admin
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ankiitsingh21/jp-application
        context: application
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ankiitsingh21/jp-auth
        context: auth
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ankiitsingh21/jp-job
        context: job
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ankiitsingh21/jp-master-data
        context: master-data
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ankiitsingh21/jp-notification
        context: notification
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ankiitsingh21/jp-worker
        context: worker
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .