apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ankiitsingh21/jp-auth
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres-auth-srv:5432/auth"
            - name: REDIS_URL
              value: "redis://redis-auth-srv:6379"
            - name: NATS_URL
              value: "nats://nats-srv:4222"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: internal-api-key-secret
                  key: INTERNAL_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000